service: chaos-slackbot

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage}
  region: ${opt:region}

package:
 include:
   - lib/

functions:
  handle:
    handler: lib/lambda.handle
    timeout: 90
    events:
      - http:
          path: handle
          method: post

plugins:
  - serverless-offline
