service: chaos-slackbot

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage}
  region: ${opt:region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sdb:*"
      Resource: "*"

package:
 include:
   - conf/
   - lib/

functions:
  handle:
    handler: lib/lambda.handle
    timeout: 90
    events:
      - http:
          path: handle
          method: post

resources:
  Resources:
    chaosSDB:
      Type: AWS::SDB::Domain
      Properties:
        Description: sdb

plugins:
  - serverless-offline
